// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cleverbit.CodingTask.Data.Models
{
    public partial class Guess
    {
        [Key]
        public int UserId { get; set; }
        [Key]
        public int MatchNo { get; set; }
        public int? GuessedNumber { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Guesses")]
        public virtual User User { get; set; }
    }
}