// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cleverbit.CodingTask.Data.Models
{
    public partial class Match
    {
        [Key]
        public int MatchNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ExpiryTime { get; set; }
        public string Winner { get; set; }
    }
}