// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cleverbit.CodingTask.Data.Models
{
    public partial class User
    {
        public User()
        {
            Guesses = new HashSet<Guess>();
        }

        [Key]
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Guess> Guesses { get; set; }
    }
}